/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProjectsProjectIdImport } from './routes/projects.$projectId'
import { Route as ProjectsProjectIdIndexImport } from './routes/projects.$projectId.index'
import { Route as ProjectsProjectIdBoardImport } from './routes/projects.$projectId.board'
import { Route as ProjectsProjectIdBacklogImport } from './routes/projects.$projectId.backlog'

// Create/Update Routes

const ProjectsProjectIdRoute = ProjectsProjectIdImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)

const ProjectsProjectIdBoardRoute = ProjectsProjectIdBoardImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)

const ProjectsProjectIdBacklogRoute = ProjectsProjectIdBacklogImport.update({
  id: '/backlog',
  path: '/backlog',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdImport
      parentRoute: typeof rootRoute
    }
    '/projects/$projectId/backlog': {
      id: '/projects/$projectId/backlog'
      path: '/backlog'
      fullPath: '/projects/$projectId/backlog'
      preLoaderRoute: typeof ProjectsProjectIdBacklogImport
      parentRoute: typeof ProjectsProjectIdImport
    }
    '/projects/$projectId/board': {
      id: '/projects/$projectId/board'
      path: '/board'
      fullPath: '/projects/$projectId/board'
      preLoaderRoute: typeof ProjectsProjectIdBoardImport
      parentRoute: typeof ProjectsProjectIdImport
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexImport
      parentRoute: typeof ProjectsProjectIdImport
    }
  }
}

// Create and export the route tree

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdBacklogRoute: typeof ProjectsProjectIdBacklogRoute
  ProjectsProjectIdBoardRoute: typeof ProjectsProjectIdBoardRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdBacklogRoute: ProjectsProjectIdBacklogRoute,
  ProjectsProjectIdBoardRoute: ProjectsProjectIdBoardRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

export interface FileRoutesByFullPath {
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/$projectId/backlog': typeof ProjectsProjectIdBacklogRoute
  '/projects/$projectId/board': typeof ProjectsProjectIdBoardRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
}

export interface FileRoutesByTo {
  '/projects/$projectId/backlog': typeof ProjectsProjectIdBacklogRoute
  '/projects/$projectId/board': typeof ProjectsProjectIdBoardRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/$projectId/backlog': typeof ProjectsProjectIdBacklogRoute
  '/projects/$projectId/board': typeof ProjectsProjectIdBoardRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/projects/$projectId'
    | '/projects/$projectId/backlog'
    | '/projects/$projectId/board'
    | '/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/projects/$projectId/backlog'
    | '/projects/$projectId/board'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/projects/$projectId'
    | '/projects/$projectId/backlog'
    | '/projects/$projectId/board'
    | '/projects/$projectId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/projects/$projectId"
      ]
    },
    "/projects/$projectId": {
      "filePath": "projects.$projectId.jsx",
      "children": [
        "/projects/$projectId/backlog",
        "/projects/$projectId/board",
        "/projects/$projectId/"
      ]
    },
    "/projects/$projectId/backlog": {
      "filePath": "projects.$projectId.backlog.jsx",
      "parent": "/projects/$projectId"
    },
    "/projects/$projectId/board": {
      "filePath": "projects.$projectId.board.jsx",
      "parent": "/projects/$projectId"
    },
    "/projects/$projectId/": {
      "filePath": "projects.$projectId.index.jsx",
      "parent": "/projects/$projectId"
    }
  }
}
ROUTE_MANIFEST_END */
